### ISSUE TITLE
New Site Look

### ISSUE THREAD

**Issue by daniel4-scratch** [ScratchFormat/scratchformat.github.io#3]
@pufflegamerz 
As I have some great knowlege of css I made a new looking site and see if you want to this repo to contain the new site so it goes under scratchformat.github.io.

https://scratchformat.glitch.me

**Comment by petabyt** [comment]
The tiny and really simple site was intentional. I wanted to make something really tiny and simple. But your version looks better, we can do that.

There is one issue, JS is required to run the page. If you could make it just HTML/CSS, that would be great. Thanks for helping out.

**Comment by daniel4-scratch** [comment]
> There is one issue, JS is required to run the page. If you could make it just HTML/CSS, that would be great. Thanks for helping out.

You looked a the source code didnt you? I knew this would be and issue for you. 

So I made the site with JS so if I chnage the Navbar or footer, it would update to all pages so I didnt have to go around changing the html files which would be a pain to do over and over agian. I want the website somthing like the [SnapWiki](https://github.com/snapwiki/snapwiki.github.io)'s website
I will need to get around this with some help.
**or**
we just stick pure html and css

**Comment by petabyt** [comment]
I thought I wrote a response... Guess I accidentally didn't send it.

Yeah, I looked at the source. I personally believe Javascript should only be used in web apps, not things that are supposed to deliver information.

**Comment by daniel4-scratch** [comment]
> I personally believe Javascript should only be used in web apps, not things that are supposed to deliver information.

True.

 I might take a month or idk making the website without js.
